[project]
name = "eventos-tech-madrid"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ClaudiaAgromayor", email = "202102295@alu.comillas.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "httpx>=0.28.1",
    "pydantic>=2.13.5",
]

[project.scripts]
eventos-tech-madrid = "eventos_tech_madrid:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
